language: python 

python: 2.7
#sudo: false
sudo: required

git: 
  depth: 2

cache:
        directories:
                - $HOME/build/sstate-cache

env:
        - TRAVIS_BB_TARGET=gzip-native
        - TRAVIS_BB_TARGET=gcc-cross-initial-arm
        - TRAVIS_BB_TARGET=rpi-basic-image 

addons:
  apt_packages:
    - bash 
    - gawk 
    - wget 
    - git-core 
    - diffstat 
    - unzip 
    - texinfo 
    - gcc-multilib
    - build-essential
    - chrpath 
    - socat 
    - cpio  
    - locales 
    
install:
    - pip install pexpect
    - mkdir -p tar && cd tar && wget  http://ftp.gnu.org/gnu/tar/tar-latest.tar.bz2 -O - | tar xj --strip=1 && ./configure -q --prefix=$HOME && make -j4 && make install 
script:       
      - export PATH=$HOME/bin:$PATH
      - which tar
      - tar --version
      - /bin/bash -c 'export PATH=$HOME/bin:$PATH; cd $TRAVIS_BUILD_DIR; source yocto/oe-init-build-env ./build && bitbake -q ${TRAVIS_BB_TARGET}'
