language: python 

python: 2.7
sudo: false

git: 
  depth: 3

addons:
  apt_packages:
    - bash 
    - gawk 
    - wget 
    - git-core 
    - diffstat 
    - unzip 
    - texinfo 
    - gcc-multilib
    - build-essential
    - chrpath 
    - socat 
    - cpio  
    - locales 
    
install:
    - pip install pexpect       
    
script:
      - /bin/bash -c 'source yocto/oe-init-build-env ./work && bitbake core-image-minimal'
