language: python 

python: 2.7
sudo: false

git: 
  depth: 3

cache:
        directories:
                - $HOME/build/sstate-cache

env:
        - TRAVIS_BB_TARGET=rpi-basic-image
        - TRAVIS_BB_TARGET=gcc-cross-initial-arm
        - TRAVIS_BB_TARGET=gzip-native

addons:
  apt_packages:
    - bash 
    - gawk 
    - wget 
    - git-core 
    - diffstat 
    - unzip 
    - texinfo 
    - gcc-multilib
    - build-essential
    - chrpath 
    - socat 
    - cpio  
    - locales 
    
install:
    - pip install pexpect       
    
script:
      - /bin/bash -c 'source yocto/oe-init-build-env ./build && bitbake -q ${TRAVIS_BB_TARGET}'
