language: bash
sudo: false

git: 
  depth: 3

addons:
  apt_packages:
    - bash 
    - gawk 
    - wget 
    - git-core 
    - diffstat 
    - unzip 
    - texinfo 
    - gcc-multilib
    - build-essential
    - chrpath 
    - socat 
    - cpio 
    - python 
    - python3
    - python-pexpect 
    - locales 
    
install: 
       - echo 1
    
script:
      - /bin/bash -c 'source yocto/oe-init-build-env ./work && bitbake core-image-minimal'
